# Documentation: https://roots.io/trellis/docs/security/

# Which components to generate the configuration files for.
# If remote machine doesn't have an SSH server then change the ssh_client_hardening to false.
ssh_client_hardening: true              # ssh
ssh_server_hardening: true              # sshd

# Set to true if CBC for ciphers is required.
ssh_client_cbc_required: false          # ssh
ssh_server_cbc_required: false          # sshd

# Set to true if weaker HMAC mechanisms are required.
ssh_client_weak_hmac: false             # ssh
ssh_server_weak_hmac: false             # sshd

# Set to true if weaker Key-Exchange (KEX) mechanisms are required.
ssh_client_weak_kex: false              # ssh
ssh_server_weak_kex: false              # sshd

# Set to true to allow logins with passwords.
ssh_client_password_login: false        # ssh
ssh_server_password_login: false        # sshd

network_ipv6_enable: false              # sshd + ssh

# Port to which ssh-client should connect.
ssh_client_port: 22                     # ssh

# Ports on which ssh-server should listen.
ssh_server_ports:                       # sshd
  - 22

# IP addresses which ssh-server should listen to, configure for extra security.
ssh_listen_to:                          # sshd
  - 0.0.0.0

# Host keys to look for when starting SSHD.
ssh_host_key_files:                     # sshd
  - /etc/ssh/ssh_host_ed25519_key
  - /etc/ssh/ssh_host_rsa_key

# Specifies the host key algorithms that the client wants to use, in order of preference.
ssh_host_key_algorithms:                # ssh
  - ssh-ed25519-cert-v01@openssh.com
  - ssh-rsa-cert-v01@openssh.com
  - ssh-ed25519
  - ssh-rsa

# Specifies the maximum number of authentication attempts permitted per connection.
# Once the number of failures reaches half this value, additional failures are logged.
ssh_max_auth_retries: 6

ssh_client_alive_interval: 600          # sshd
ssh_client_alive_count: 3               # sshd

# Example hosts with custom options.
# ssh_remote_hosts:
#   - names:
#         - example.com
#         - example2.com
#     options:
#         - Port 2222
#         - ForwardAgent yes
#   - names:
#         - example3.com
#     options:
#         - StrictHostKeyChecking no
ssh_remote_hosts: []                     # ssh

# Set to true to allow root to login via key-based mechanism.
ssh_allow_root_with_key: false           # sshd

# Set to true to allow TCP Forwarding.
ssh_allow_tcp_forwarding: false          # sshd

# Set to false to disable Agent Forwarding.
ssh_allow_agent_forwarding: true         # sshd

# PAM authentication enabled to avoid Debian bug with openssh-server.
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=751636
# can change to `false` once Canonical Main repository includes openssh 1:7.2p2-6
ssh_use_pam: true                        # sshd

# Login is disallowed for user names that match one of the patterns.
ssh_deny_users: []                       # sshd

# Login is allowed only for user names that match one of the patterns.
ssh_allow_users: []                      # sshd

# Login is disallowed for users whose primary group or supplementary group list matches one of the patterns.
ssh_deny_groups: []                      # sshd

# Login is allowed only for users whose primary group or supplementary group list matches one of the patterns.
ssh_allow_groups: []                     # sshd

# Set to true to enable printing of the MOTD.
ssh_print_motd: false                    # sshd

# Set to true to display last login information.
ssh_print_last_log: false                # sshd

# Set to true to display /etc/ssh/banner.txt before authentication is allowed.
ssh_banner: false                        # sshd

# Set to false to disable distribution version leakage during initial protocol handshake.
ssh_print_debian_banner: false           # sshd

ssh_send_env: ''                         # ssh
ssh_accept_env: ''                       # sshd

# Set to true to enable SFTP configuration.
sftp_enabled: false

# Change default SFTP chroot location.
sftp_chroot_dir: /home/%u

# Enable experimental client roaming.
ssh_client_roaming: false

use_privilege_separation: "sandbox"       # sshd

ssh_macs_default:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - hmac-ripemd160-etm@openssh.com
  - umac-128-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256
  - hmac-ripemd160

ssh_macs_weak: "{{ ssh_macs_default + ['umac-128@openssh.com','hmac-sha1'] }}"

ssh_ciphers_default:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

ssh_ciphers_weak: "{{ ssh_ciphers_default + ['aes256-cbc', 'aes192-cbc', 'aes128-cbc'] }}"

ssh_kex_default:
  - curve25519-sha256@libssh.org
  - diffie-hellman-group-exchange-sha256

ssh_kex_weak: "{{ ssh_kex_default + ['diffie-hellman-group14-sha1', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group1-sha1'] }}"
