---
- name: Ensure necessary variables are defined
  hosts: localhost
  gather_facts: false
  vars:
    extra_vars_commands:
      server.yml: "env=<environment>"
      deploy.yml: "\"site=<domain> env=<environment>\""
      sync.yml: "\"site=<domain>, src=<source env>, dest=<destination env>\""
    # extra_vars_command: "{{ (playbook == 'sync.yml') | ternary('\"site=<domain>, src=<source env>, dest=<destination env>\"', (playbook == 'server.yml') | ternary('env=<environment>', '\"site=<domain> env=<environment>\"')) }}"
  tasks:
    - name: Ensure environment is defined
      fail:
        msg: |
          Environment missing. Use `-e` to define `env`:
          ansible-playbook {{ playbook }} -e {{ extra_vars_commands[playbook] }}
      when: playbook in ['server.yml', 'deploy.yml'] and env is not defined
      tags: [variable-check]

    - name: Ensure sync source is defined
      fail:
        msg: |
          Sync source missing. Use `-e` to define `src`:
          ansible-playbook {{ playbook }} -e {{ extra_vars_commands[playbook] }}
      when: playbook == 'sync.yml' and src is not defined
      tags: [variable-check]

    - name: Ensure sync destination is defined
      fail:
        msg: |
          Sync destination missing. Use `-e` to define `dest`:
          ansible-playbook {{ playbook }} -e {{ extra_vars_commands[playbook] }}
      when: playbook == 'sync.yml' and dest is not defined
      tags: [variable-check]
